version: '2'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: springboot
      MYSQL_ROOT_PASSWORD: springtest
  db2:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: springboot
      POSTGRES_PASSWORD: springtest